// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjjC3iG0WlLBnAsTC5JnYhamNn2Jyj5k',
    appId: '1:771167854156:web:f3fc9eff2af971ca3c9ee9',
    messagingSenderId: '771167854156',
    projectId: 'todolist-53229',
    authDomain: 'todolist-53229.firebaseapp.com',
    storageBucket: 'todolist-53229.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKfCwocZxr_C6x-K96msbeU42HbBdTtek',
    appId: '1:771167854156:android:0e625dddab85cdcc3c9ee9',
    messagingSenderId: '771167854156',
    projectId: 'todolist-53229',
    storageBucket: 'todolist-53229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKyMo0hXmlzI7FTK_26xCwOZ7meSRuRmA',
    appId: '1:771167854156:ios:d1961bee6d2dc9f93c9ee9',
    messagingSenderId: '771167854156',
    projectId: 'todolist-53229',
    storageBucket: 'todolist-53229.firebasestorage.app',
    iosBundleId: 'com.example.sqlitedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKyMo0hXmlzI7FTK_26xCwOZ7meSRuRmA',
    appId: '1:771167854156:ios:d1961bee6d2dc9f93c9ee9',
    messagingSenderId: '771167854156',
    projectId: 'todolist-53229',
    storageBucket: 'todolist-53229.firebasestorage.app',
    iosBundleId: 'com.example.sqlitedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWjjC3iG0WlLBnAsTC5JnYhamNn2Jyj5k',
    appId: '1:771167854156:web:0b95b2c3c90dfbd53c9ee9',
    messagingSenderId: '771167854156',
    projectId: 'todolist-53229',
    authDomain: 'todolist-53229.firebaseapp.com',
    storageBucket: 'todolist-53229.firebasestorage.app',
  );
}
